print("Hello World! ")
x = input("Your first name? ")
y = input("Your last name? ")
age = input("Your age? ")
city = input("Which city do you live in? ")
height = input("Whats ur height?")
print(f"Hello, {x} {y}! Your age is {age}. You live in {city}.")

print(type(y))
print(type(age))
print(age + 2)
print(height + 0.1)
